== Develop

=== Tight feedback cycle

My `.vimrc` adds this repository to `runtimepath`.
A process that works is:

. Edit `ftplugin/jsonnet.vim`
. Re-open a Jsonnet file
. Script is re-sourced

== Design

=== Feature goals

==== First version

* [x] Show current _context_ of plugin (i.e. Tanka environment `baseDir`).
This should be a statusline thing or something.
* [x] Jump to file in import statement, using proper path searching rules.
See https://tanka.dev/libraries/import-paths
* [ ] Search for word under cursor in all imported files (for current _context_)
* [ ] Test changing Tanka envs while vim-tanka is already enabled (with a different env)
* [ ] More testing with weird window states.
Sometimes `:TankaSetEnv` leaves Vim in a weird state.
I'm not sure `winrestview()` is actually working the way I think it should.
* [ ] Write README.

==== Later versions

* [ ] Integration of tk/jsonnet errors into quickfix.
Parse error messages, extract line numbers, populate quickfix list.
* [ ] Auto-complete for function arguments (hover tooltip)
* [ ] Auto-complete for object fields.
Sorta needs an lenient parser like tree-sitter.
Or a hacky option is periodically running `tk eval` and caching the results.
When `tk eval` fails, just use the latest cached result for completion.
Updating cache could happen on a timer or on e.g. `BufWrite`.
* [ ] Document how to add the _context_ to an existing statusline setup (e.g. with arline, powerline, etc.)

== Bugs

* When calling `:TankaSetEnv`, the cursor doesn't always stay in the same window.
** I had a faulty underestanding of `winsaveview()` and `winrestview()`:
they only work on a single window, and doesn't even save which buffer was loaded.
** The `bufdo` command is probably why the current buffer at the end isn't correct.
** Instead of `winsaveview()` and `winresetview()` I think I just need this:
*** Save current buffer number.
*** Run `bufdo` command to set 'path'
*** Restore original buffer
*** Save current window number
*** Run `windo` command to update 'statusline'
*** Run `execute nr . 'wincmd w'` to restore focus to original window.
* `:TankaSetEnv` and `:TankaOff` print a bunch of window names to the screen.
Kind annoying.

== Notes

* Checkout the syntastic integration in `vim-jsonnet`: https://github.com/google/vim-jsonnet/pull/1
* Jsonnet AST explorer thing: https://github.com/fkling/astexplorer/pull/505
* https://github.com/returntocorp/semgrep
* https://web.archive.org/web/20210516102739/https://vimways.org/2018/death-by-a-thousand-files/
* https://teukka.tech/vimcandothat.html
